### ISSUE TITLE
ImportError: No module named 'vine'

### ISSUE THREAD

**Issue by marceloleiva** [PyAr/pyarweb#365]
Hola, estoy tratando de instalar pyarweb en Docker pero al correr ```docker-compose run web ./initialize.sh``` obtengo el siguiente error:     

```
[10:02:19] Marcelo:pyarweb git:(master) $ docker-compose run web ./initialize.sh
Creating network "pyarweb_default" with the default driver
Creating volume "pyarweb_redisdata" with default driver
Creating volume "pyarweb_pgdata" with default driver
Pulling redis (redis:latest)...
latest: Pulling from library/redis
75a822cd7888: Pull complete
e40c2fafe648: Pull complete
ce384d4aea4f: Pull complete
5e29dd684b84: Pull complete
29a3c975c335: Pull complete
a405554540f9: Pull complete
4b2454731fda: Pull complete
Digest: sha256:eed4da4937cb562e9005f3c66eb8c3abc14bb95ad497c03dc89d66bcd172fc7f
Status: Downloaded newer image for redis:latest
Pulling postgres (postgres:latest)...
latest: Pulling from library/postgres
75a822cd7888: Already exists
68f8c57d4ec8: Pull complete
1ee19503c02a: Pull complete
ea8f451ca276: Pull complete
bce67042ed9c: Pull complete
eb0990abb35a: Pull complete
af6ba638869d: Pull complete
e8d456ed70c7: Pull complete
1d9946f84913: Pull complete
aaaf404de7ad: Pull complete
6cd7c84ea195: Pull complete
Digest: sha256:855b55b060bfa63cb39bfee0fe4ec6f40037e9f85f8a7eec24bc8e59ec1a8345
Status: Downloaded newer image for postgres:latest
Creating pyarweb_postgres_1
Creating pyarweb_redis_1
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.4/dist-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.4/dist-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.4/dist-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/code/pyarweb/settings.py", line 96, in <module>
    import djcelery
  File "/usr/local/lib/python3.4/dist-packages/djcelery/__init__.py", line 34, in <module>
    from celery import current_app as celery  # noqa
  File "/usr/local/lib/python3.4/dist-packages/celery/__init__.py", line 149, in <module>
    from . import local  # noqa
  File "/usr/local/lib/python3.4/dist-packages/celery/local.py", line 15, in <module>
    from .five import bytes_if_py2, items, string, string_t
  File "/usr/local/lib/python3.4/dist-packages/celery/five.py", line 5, in <module>
    import vine.five
ImportError: No module named 'vine'
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.4/dist-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.4/dist-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.4/dist-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/code/pyarweb/settings.py", line 96, in <module>
    import djcelery
  File "/usr/local/lib/python3.4/dist-packages/djcelery/__init__.py", line 34, in <module>
    from celery import current_app as celery  # noqa
  File "/usr/local/lib/python3.4/dist-packages/celery/__init__.py", line 149, in <module>
    from . import local  # noqa
  File "/usr/local/lib/python3.4/dist-packages/celery/local.py", line 15, in <module>
    from .five import bytes_if_py2, items, string, string_t
  File "/usr/local/lib/python3.4/dist-packages/celery/five.py", line 5, in <module>
    import vine.five
ImportError: No module named 'vine'
```    

Estoy usando OSX El Capitán y Docker 1.11.2

**Comment by lecovi** [comment]
Ahora estamos subiendo lo nuevo en docker-compose.
Fixed!
