### ISSUE TITLE
ERROR: events.tests.test_event_participation

### ISSUE THREAD

**Issue by eamanu** [PyAr/pyarweb#402]
En la rama 'dev' 

Cuando se ejecuta `./manage.py test` se obtiene el siguiente error:

======================================================================
ERROR: events.tests.test_event_participation (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib/python3.4/unittest/case.py", line 577, in run
    testMethod()
  File "/usr/lib/python3.4/unittest/loader.py", line 32, in testFailure
    raise exception
ImportError: Failed to import test module: events.tests.test_event_participation
Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/loader.py", line 312, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.4/unittest/loader.py", line 290, in _get_module_from_name
    __import__(name)
  File "/home/eamanu/dev/pyarweb/events/tests/test_event_participation.py", line 6, in <module>
    from events.tests.factories import EventParticipationFactory, UserFactory
  File "/home/eamanu/dev/pyarweb/events/tests/factories.py", line 3, in <module>
    from factory import SubFactory, Sequence
ImportError: No module named 'factory'

----------------------------------------------------------------------
Ran 14 tests in 1.224s

FAILED (errors=1)

**Comment by eamanu** [comment]
Se solucionó instalando `factory_boy`.

Por favor se debe agregar el en el `requirements.txt `

**Comment by cmdelatorre** [comment]
Fijate que hay un [dev_requirements.txt](https://github.com/PyAr/pyarweb/blob/dev/dev_requirements.txt) en el repo. Son los paquetes que hay que instalar para desarrollo.
Estaba desactualizada la documentación: https://github.com/PyAr/pyarweb/wiki/Instalaci%C3%B3n-manual
Ahí la actualicé.
